import type { Metadata } from 'next'
import {Inter} from "next/font/google"
import './globals.css'

const inter= Inter({subsets:["latin"]})

export const metadata: Metadata = {
   
    title:"Creat ToDo App",
    description:"Generated by Power of CSS Flex box",
}
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
      <html lang="en">
        <body >{children}</body>
      </html>
      
    )
  }